#!/bin/bash

DNAME=trixiekeys

. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
    start)
        stat_busy "Starting TrixieKeys daemon"

        /usr/bin/trixiekeys "AT Translated Set 2 keyboard"
        #"USB Keyboard"

        if [[ $? -gt 0 ]]; then
            stat_fail
        else
            add_daemon $DNAME
            stat_done
        fi
    ;;
    stop)
        stat_busy "Stopping TrixieKeys daemon"

        killall trixiekeys

        if [[ $? -gt 0 ]]; then
            stat_fail
        else
            rm_daemon $DNAME
            stat_done
        fi
    ;;
    restart)
        $0 stop
        sleep 1
        $0 start
    ;;
    *)
        echo "usage: $0 {start|stop|restart}"
esac
exit 0


